import type { Metadata } from "next";
// import { Inter } from "next/font/google";


// const inter = Inter({ subsets: ["latin"] });

// Third-party Imports
import 'react-perfect-scrollbar/dist/css/styles.css'

// Type Imports
import type { ChildrenType } from '@/core/types'

// Style Imports
import '@/app/globals.css'

export const metadata: Metadata = {
  title: "Irrigation App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: ChildrenType) => {
  // Vars
  const direction = 'ltr'

  return (
    <html id='__next' dir={direction}>
      <body className='flex is-full min-bs-full flex-auto flex-col'>{children}</body>
    </html>
  )
}

export default RootLayout





// // Generated Icon CSS Imports
// import '@assets/iconify-icons/generated-icons.css'

// export const metadata = {
//   title: 'Demo: Materio - NextJS Dashboard Free',
//   description:
//     'Develop next-level web apps with Materio Dashboard Free - NextJS. Now, updated with lightning-fast routing powered by MUI and App router.'
// }

// const RootLayout = ({ children }: ChildrenType) => {
//   // Vars
//   const direction = 'ltr'

//   return (
//     <html id='__next' dir={direction}>
//       <body className='flex is-full min-bs-full flex-auto flex-col'>{children}</body>
//     </html>
//   )
// }

// export default RootLayout

