# Generated by Django 4.2.14 on 2024-07-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_culture', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('capacite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerreCulture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('numero_serre', models.CharField(max_length=8, unique=True)),
                ('superficie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.planche')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseFertilisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_fertilisation', models.CharField(max_length=255)),
                ('periode_fertilisation', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.culture')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseCulture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=255)),
                ('periode_phase', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.culture')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseCroissance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_croissance', models.CharField(max_length=255)),
                ('periode_croissance', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Humidite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('serre_culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.serreculture')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenceRemplissage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periode_remplissage', models.DateTimeField()),
                ('tanque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('phase_fertilisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.phasefertilisation')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilisant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fertilisant', models.CharField(max_length=255)),
                ('quantite', models.FloatField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('phase_fertilisation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.phasefertilisation')),
            ],
        ),
        migrations.CreateModel(
            name='CultureSurface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.culture')),
                ('surface_culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.serreculture')),
            ],
        ),
        migrations.CreateModel(
            name='Capteur_Serre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('capteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.capteur')),
                ('serre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.serreculture')),
            ],
        ),
    ]
