# Generated by Django 4.2.14 on 2024-07-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_culture', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SerreCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('pompe', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('capacite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('date_ajout', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PhaseCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=255)),
                ('periode_phase', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.culture')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenceRemplissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_remplissage', models.DateTimeField()),
                ('tanque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('phase_culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.phaseculture')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilisant', models.CharField(max_length=255)),
                ('quantite', models.FloatField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('phase_culture_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.phaseculture')),
            ],
        ),
        migrations.CreateModel(
            name='CultureSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.culture')),
                ('surface_culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.serreculture')),
            ],
        ),
        migrations.CreateModel(
            name='CapteurHumidite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('value', models.FloatField()),
                ('surface_culture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.planche')),
            ],
        ),
    ]
