# Generated by Django 4.2.14 on 2024-07-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_capteurhumidite_id_alter_culture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaseculture',
            name='periode_phase',
            field=models.IntegerField(),
        ),
    ]
